#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Store-Plucene
version:      0.02
version_from: Plucene.pm
installdirs:  site
requires:
    Email::Folder:                 0
    Email::Store:                  0
    Plucene::Simple:               1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
